import * as Icons from "../../components/Icons";

export const menus = [
  {
    id: "dealership",
    name: "dealership",
    icon: <Icons.DealershipIcon />,
    iconActive: <Icons.DealershipIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "bank",
    name: "bank",
    icon: <Icons.BankIcon />,
    iconActive: <Icons.BankIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "garage",
    name: "garage",
    icon: <Icons.GarageIcon />,
    iconActive: <Icons.GarageIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "speedshop",
    name: "speedshop",
    icon: <Icons.SpeedshopIcon />,
    iconActive: <Icons.SpeedshopIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "marketplace",
    name: "marketplace",
    icon: <Icons.MarketplaceIcon />,
    iconActive: <Icons.MarketplaceIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "trade",
    name: "trade",
    icon: <Icons.TradeIcon />,
    iconActive: <Icons.TradeIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: true,
  },
  {
    id: "farms",
    name: "trade/farms",
    icon: <Icons.FarmsIcon />,
    iconActive: <Icons.FarmsIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
  },
  {
    id: "pools",
    name: "trade/pools",
    icon: <Icons.PoolsIcon />,
    iconActive: <Icons.PoolsIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
  },
  {
    id: "swap",
    name: "trade/swap",
    icon: <Icons.SwapIcon />,
    iconActive: <Icons.SwapIcon color={`#23D0FF`} />,
    isSubMenu: true,
    hasSubMenu: false,
  },
  {
    id: "games",
    name: "games",
    icon: <Icons.GamesIcon />,
    iconActive: <Icons.GamesIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
  {
    id: "bridge",
    name: "bridge",
    icon: <Icons.BridgeIcon />,
    iconActive: <Icons.BridgeIcon color={`#FFAE00`} />,
    isSubMenu: false,
    hasSubMenu: false,
  },
];
